name: Auto Commit

on:
  schedule:
    - cron: "0 10 * * *" # Todos los días a las 10 AM UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Hacer cambios diarios
        run: echo "Última actualización: $(date -u)" > daily_commit.txt

      - name: Configurar Git
        run: |
          git config --global user.name "cuentaperuana"
          git config --global user.email "cuentaperuana@outlook.com"

      - name: Commit y push
        run: |
          git add daily_commit.txt
          git commit -m "Commit automático - $(date -u)"
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
