name: Random Daily Commit

on:
  schedule:
    - cron: '32 12 * * *' # Hora en UTC – cambia para que parezca más natural
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Randomize file content
        run: |
          echo "$(date) - Random content $RANDOM" >> activity.log

      - name: Git config
        run: |
          git config --global user.email "cuentaperuana@outlook.com"
          git config --global user.name "cuentaperuana"

      - name: Commit changes
        run: |
          git add activity.log
          git commit -m "Daily commit 🤖" || echo "No changes to commit"
          git push
